/**
 * Mobile-only UI strings not (yet) in @khoroch/core's DICT.
 * Bengali-first defaults with English parity, mirroring core's i18n shape.
 * Promote to packages/core/src/i18n.ts when keys are needed cross-app.
 */
import type * as api from "./api";

export const STRINGS = {
  bn: {
    account: "অ্যাকাউন্ট",
    signingIn: "লগইন হচ্ছে…",
    errBadCreds: "ইমেইল বা পাসওয়ার্ড সঠিক নয়।",
    errNetwork: "সার্ভারে পৌঁছানো যাচ্ছে না — ইন্টারনেট সংযোগ দেখুন।",
    errGeneric: "কিছু একটা সমস্যা হয়েছে। আবার চেষ্টা করুন।",

    // Expenses list (T3.1)
    expensesTitle: "খরচসমূহ",
    addExpenseBtn: "নতুন খরচ",
    loadingList: "খরচ লোড হচ্ছে…",
    emptyList: "এখনও কোনো খরচ নেই।",
    emptyListHint: "নিচের বাটন থেকে প্রথম খরচটি যোগ করুন।",
    loadMore: "আরও দেখুন",
    loadingMore: "আরও আনা হচ্ছে…",
    retry: "আবার চেষ্টা করুন",
    entriesLoaded: "টি এন্ট্রি দেখানো হচ্ছে",

    // Add expense form (T3.1)
    addTitle: "খরচ যোগ করুন",
    amount: "পরিমাণ (টাকা)",
    amountPlaceholder: "যেমন: 890",
    category: "খাত",
    categoryPlaceholder: "যেমন: চা, রিকশা, কাঁচাবাজার",
    groupLabel: "গ্রুপ",
    payLabel: "পেমেন্ট মাধ্যম",
    dateLabel: "তারিখ (YYYY-MM-DD)",
    descLabel: "বিবরণ (ঐচ্ছিক)",
    descPlaceholder: "যেমন: সপ্তাহের বাজার",
    save: "সংরক্ষণ করুন",
    saving: "সংরক্ষণ হচ্ছে…",
    errAmount: "সঠিক পরিমাণ লিখুন (০ এর বেশি)।",
    errCategory: "খাতের নাম লিখুন।",
    errDate: "তারিখ YYYY-MM-DD ফরম্যাটে দিন।",
    errUnauthorized: "সেশন শেষ হয়ে গেছে — আবার লগইন করুন।",

    // Dashboard (T3.4)
    openDashboard: "ড্যাশবোর্ড",
    dashboardTitle: "মাসিক হিসাব",
    monthTotal: "এই মাসের মোট খরচ",
    monthCount: "টি এন্ট্রি",
    byGroup: "গ্রুপ অনুযায়ী",
    recentExpenses: "সাম্প্রতিক খরচ",
    noExpensesThisMonth: "এই মাসে কোনো খরচ নেই।",
    openDebts: "ধার-দেনা",

    // Debts (T3.4)
    debtsTitle: "ধার-দেনা",
    statusOpen: "চলমান",
    statusSettled: "পরিশোধিত",
    statusAll: "সব",
    dirLend: "ধার দিয়েছি",
    dirBorrow: "ধার নিয়েছি",
    addDebt: "নতুন ধার",
    party: "কার সাথে",
    partyPlaceholder: "যেমন: রফিক, করিম চাচা",
    dirLabel: "ধারের ধরন",
    noteLabel: "নোট (ঐচ্ছিক)",
    notePlaceholder: "যেমন: বাসা ভাড়ার অগ্রিম",
    loadingDebts: "ধার লোড হচ্ছে…",
    emptyDebts: "কোনো ধার নেই।",
    emptyDebtsHint: "নিচের বাটন থেকে প্রথম ধারটি যোগ করুন।",
    pay: "পরিশোধ",
    payTitle: "পরিশোধের পরিমাণ (টাকা)",
    payPlaceholder: "যেমন: 500",
    confirmPay: "পরিশোধ করুন",
    paying: "পরিশোধ হচ্ছে…",
    payFull: "সম্পূর্ণ পরিশোধিত ✓",
    payPartial: "আংশিক পরিশোধ — বাকি",
    settledOn: "পরিশোধিত হয়েছে",
    cancel: "বাতিল",
    errParty: "কার সাথে ধার, লিখুন।",
    errDebtAmount: "সঠিক পরিমাণ লিখুন (০ এর বেশি)।",

    // Report (T5.1)
    reportTitle: "রিপোর্ট",
    modeMonthly: "মাসিক",
    modeYearly: "বার্ষিক",
    yearTotal: "এই বছরের মোট খরচ",
    loadingReport: "রিপোর্ট লোড হচ্ছে…",
    noExpensesThisYear: "এই বছরে কোনো খরচ নেই।",
    byMonth: "মাস অনুযায়ী",
    prevYear: "আগের বছর",
    nextYear: "পরের বছর",

    // Budget (T10.1)
    budgetTitle: "বাজেট",
    budgetMonth: "মাস",
    prevMonth: "আগের মাস",
    nextMonth: "পরের মাস",
    budgetLimit: "মাসিক সীমা (৳)",
    budgetLimitPlaceholder: "যেমন: 20000",
    budgetSpent: "খরচ",
    budgetUsed: "ব্যবহৃত",
    budgetCats: "খাতভিত্তিক বাজেট",
    budgetLoading: "বাজেট লোড হচ্ছে…",
    budgetNoLimit: "সীমা নির্ধারিত নেই — উপরে সীমা দিন।",
    budgetNoCats: "এই মাসে খাতভিত্তিক তথ্য নেই।",
    budgetNoCatLimit: "সীমা নেই",
    budgetStatusOk: "ভালো",
    budgetStatusWarn: "সতর্ক",
    budgetStatusOver: "সীমা ছাড়িয়ে",
    budgetSaved: "সংরক্ষিত ✓",
    budgetEditCatLimit: "সীমা বদলান",
    errBudgetLimit: "সঠিক সীমা লিখুন (০ এর বেশি)।",

    // Settings (T11.3)
    settings: "সেটিংস",
    profile: "প্রোফাইল",
    name: "নাম",
    email: "ইমেইল",
    language: "ভাষা",
    theme: "থিম",
    light: "লাইট",
    dark: "ডার্ক",
    langBn: "বাংলা",
    langEn: "English",
    voiceLang: "ভয়েস ভাষা",
    voiceLangValue: "বাংলা (bn-BD)",
    version: "ভার্সন",
    logout: "লগ আউট",
  },
  en: {
    account: "Account",
    signingIn: "Signing in…",
    errBadCreds: "Incorrect email or password.",
    errNetwork: "Cannot reach the server — check your connection.",
    errGeneric: "Something went wrong. Please try again.",

    // Expenses list (T3.1)
    expensesTitle: "Expenses",
    addExpenseBtn: "New expense",
    loadingList: "Loading expenses…",
    emptyList: "No expenses yet.",
    emptyListHint: "Add your first expense with the button below.",
    loadMore: "Load more",
    loadingMore: "Loading more…",
    retry: "Try again",
    entriesLoaded: "entries shown",

    // Add expense form (T3.1)
    addTitle: "Add expense",
    amount: "Amount (taka)",
    amountPlaceholder: "e.g. 890",
    category: "Category",
    categoryPlaceholder: "e.g. tea, rickshaw, groceries",
    groupLabel: "Group",
    payLabel: "Payment method",
    dateLabel: "Date (YYYY-MM-DD)",
    descLabel: "Description (optional)",
    descPlaceholder: "e.g. weekly groceries",
    save: "Save",
    saving: "Saving…",
    errAmount: "Enter a valid amount (greater than 0).",
    errCategory: "Enter a category name.",
    errDate: "Enter the date as YYYY-MM-DD.",
    errUnauthorized: "Session expired — please sign in again.",

    // Dashboard (T3.4)
    openDashboard: "Dashboard",
    dashboardTitle: "Monthly summary",
    monthTotal: "This month's total",
    monthCount: "entries",
    byGroup: "By group",
    recentExpenses: "Recent expenses",
    noExpensesThisMonth: "No expenses this month.",
    openDebts: "Debts",

    // Debts (T3.4)
    debtsTitle: "Debts",
    statusOpen: "Open",
    statusSettled: "Settled",
    statusAll: "All",
    dirLend: "Lent out",
    dirBorrow: "Borrowed",
    addDebt: "New debt",
    party: "Party",
    partyPlaceholder: "e.g. Rafik, Uncle Karim",
    dirLabel: "Direction",
    noteLabel: "Note (optional)",
    notePlaceholder: "e.g. rent advance",
    loadingDebts: "Loading debts…",
    emptyDebts: "No debts yet.",
    emptyDebtsHint: "Add your first debt with the button below.",
    pay: "Pay back",
    payTitle: "Payment amount (taka)",
    payPlaceholder: "e.g. 500",
    confirmPay: "Confirm payment",
    paying: "Paying…",
    payFull: "Fully settled ✓",
    payPartial: "Partially paid — remaining",
    settledOn: "Settled on",
    cancel: "Cancel",
    errParty: "Enter who the debt is with.",
    errDebtAmount: "Enter a valid amount (greater than 0).",

    // Report (T5.1)
    reportTitle: "Report",
    modeMonthly: "Monthly",
    modeYearly: "Yearly",
    yearTotal: "This year's total",
    loadingReport: "Loading report…",
    noExpensesThisYear: "No expenses this year.",
    byMonth: "By month",
    prevYear: "Previous year",
    nextYear: "Next year",

    // Budget (T10.1)
    budgetTitle: "Budget",
    budgetMonth: "Month",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    budgetLimit: "Monthly limit (৳)",
    budgetLimitPlaceholder: "e.g. 20000",
    budgetSpent: "Spent",
    budgetUsed: "Used",
    budgetCats: "Category budgets",
    budgetLoading: "Loading budget…",
    budgetNoLimit: "No limit set — set one above.",
    budgetNoCats: "No category data for this month.",
    budgetNoCatLimit: "No limit",
    budgetStatusOk: "Good",
    budgetStatusWarn: "Watch",
    budgetStatusOver: "Over limit",
    budgetSaved: "Saved ✓",
    budgetEditCatLimit: "Edit limit",
    errBudgetLimit: "Enter a valid limit (greater than 0).",

    // Settings (T11.3) — segment labels stay বাংলা/English in both locales,
    // and the voice chip stays bn-BD (matches the prototype).
    settings: "Settings",
    profile: "Profile",
    name: "Name",
    email: "Email",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    langBn: "বাংলা",
    langEn: "English",
    voiceLang: "Voice language",
    voiceLangValue: "বাংলা (bn-BD)",
    version: "Version",
    logout: "Log out",
  },
} as const;

/** Short month labels for the yearly by_month mini chart (index 0 = January). */
export const MONTH_LABELS: Record<"bn" | "en", readonly string[]> = {
  bn: [
    "জানু",
    "ফেব",
    "মার্চ",
    "এপ্রিল",
    "মে",
    "জুন",
    "জুলাই",
    "আগ",
    "সেপ্ট",
    "অক্টো",
    "নভে",
    "ডিসে",
  ],
  en: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
};

export type MobileStringKey = keyof typeof STRINGS.bn;

/** UI language — "bn" is the Bengali-first default. */
export type Lang = keyof typeof STRINGS;

/** Bengali labels for the API's 8 expense groups (grp column). */
export const GROUP_LABELS: Record<api.ExpenseGroup, string> = {
  food: "খাবার",
  housing: "বাসা",
  utility: "ইউটিলিটি",
  transport: "যাতায়াত",
  health: "স্বাস্থ্য",
  education: "শিক্ষা",
  personal: "ব্যক্তিগত",
  other: "অন্যান্য",
};

/** Bengali labels for the API's 6 payment methods (pay column). */
export const PAY_LABELS: Record<api.PayMethod, string> = {
  cash: "নগদ টাকা",
  bkash: "বিকাশ",
  nagad: "নগদ",
  rocket: "রকেট",
  card: "কার্ড",
  bank: "ব্যাংক",
};
