/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and start a session (401 with a uniform message).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the caller's session and its current refresh token (204).
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user's public profile.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate a refresh token; reuse of an old token revokes the session.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a profile and start a session (201 with a fresh token pair).
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Expenses
         * @description List the caller's expenses, newest first, keyset-paginated.
         */
        get: operations["list_expenses_api_v1_expenses_get"];
        put?: never;
        /**
         * Create Expense
         * @description Record one expense (201 with the stored row).
         */
        post: operations["create_expense_api_v1_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Expenses Bulk
         * @description Insert up to 50 expenses for the caller in a single flush.
         */
        post: operations["create_expenses_bulk_api_v1_expenses_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Expense
         * @description Delete the caller's expense (204; unknown/foreign id → 404).
         */
        delete: operations["delete_expense_api_v1_expenses__expense_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Expense
         * @description Partially update the caller's expense (omitted fields stay as-is).
         */
        patch: operations["update_expense_api_v1_expenses__expense_id__patch"];
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly Report
         * @description Aggregates for one month (``?ym=YYYY-MM``, default: current month).
         */
        get: operations["monthly_report_api_v1_reports_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/yearly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yearly Report
         * @description Aggregates for one year (``?year=YYYY``, default: current year).
         */
        get: operations["yearly_report_api_v1_reports_yearly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Transcript
         * @description Rule-parse a Bengali voice transcript into expense candidates.
         */
        post: operations["parse_transcript_api_v1_voice_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthOut
         * @description Login/register/refresh response: user + token pair.
         */
        AuthOut: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * BulkExpensesIn
         * @description POST /expenses/bulk body (voice multi-item inserts).
         */
        BulkExpensesIn: {
            /** Items */
            items: components["schemas"]["ExpenseIn"][];
        };
        /** BulkExpensesOut */
        BulkExpensesOut: {
            /** Items */
            items: components["schemas"]["ExpenseOut"][];
        };
        /**
         * ExpenseIn
         * @description POST /expenses and POST /expenses/bulk item body.
         */
        ExpenseIn: {
            /**
             * Amt
             * @example 890.00
             */
            amt: string;
            /** Cat */
            cat: string;
            /** Desc */
            desc?: string | null;
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /**
             * Iso
             * Format: date
             */
            iso: string;
            /**
             * Pay
             * @default cash
             * @enum {string}
             */
            pay: "cash" | "bkash" | "nagad" | "rocket" | "card" | "bank";
        };
        /**
         * ExpenseListOut
         * @description Envelope for every list endpoint (ADR-0004 §8).
         */
        ExpenseListOut: {
            /** Items */
            items: components["schemas"]["ExpenseOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * ExpenseOut
         * @description Public expense row; keys mirror the DB columns exactly.
         */
        ExpenseOut: {
            /** Amt */
            amt: string;
            /** Cat */
            cat: string;
            /** Created At */
            created_at: string;
            /** Desc */
            desc?: string | null;
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /** Id */
            id: string;
            /**
             * Iso
             * Format: date
             */
            iso: string;
            /**
             * Pay
             * @enum {string}
             */
            pay: "cash" | "bkash" | "nagad" | "rocket" | "card" | "bank";
            /** User Id */
            user_id: string;
        };
        /**
         * ExpenseUpdate
         * @description PATCH /expenses/{id} body — every field optional (partial update).
         */
        ExpenseUpdate: {
            /** Amt */
            amt?: string | null;
            /** Cat */
            cat?: string | null;
            /** Desc */
            desc?: string | null;
            /** Grp */
            grp?: ("food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other") | null;
            /** Iso */
            iso?: string | null;
            /** Pay */
            pay?: ("cash" | "bkash" | "nagad" | "rocket" | "card" | "bank") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Healthz */
        Healthz: {
            /** Env */
            env: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * LoginIn
         * @description POST /auth/login body.
         */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MonthlyReportOut */
        MonthlyReportOut: {
            /** By Day */
            by_day: components["schemas"]["ReportByDay"][];
            /** By Group */
            by_group: {
                [key: string]: string;
            };
            /** Count */
            count: number;
            /** Total */
            total: string;
            /** Ym */
            ym: string;
        };
        /**
         * ParsedItem
         * @description One expense candidate extracted from a transcript segment.
         */
        ParsedItem: {
            /** Amt */
            amt: string;
            /** Cat */
            cat: string;
            /** Desc */
            desc?: string | null;
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /** Iso */
            iso?: string | null;
            /** Pay */
            pay?: ("cash" | "bkash" | "nagad" | "rocket" | "card" | "bank") | null;
        };
        /**
         * RefreshIn
         * @description POST /auth/refresh body.
         */
        RefreshIn: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * RegisterIn
         * @description POST /auth/register body.
         */
        RegisterIn: {
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** Password */
            password: string;
        };
        /** ReportByDay */
        ReportByDay: {
            /**
             * Iso
             * Format: date
             */
            iso: string;
            /** Total */
            total: string;
        };
        /** ReportByMonth */
        ReportByMonth: {
            /** Total */
            total: string;
            /** Ym */
            ym: string;
        };
        /**
         * UserOut
         * @description Public view of a profile.
         */
        UserOut: {
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoiceParseIn
         * @description POST /voice/parse body.
         */
        VoiceParseIn: {
            /** Text */
            text: string;
        };
        /** VoiceParseOut */
        VoiceParseOut: {
            /** Confidence */
            confidence: number;
            /** Items */
            items: components["schemas"]["ParsedItem"][];
        };
        /** YearlyReportOut */
        YearlyReportOut: {
            /** By Group */
            by_group: {
                [key: string]: string;
            };
            /** By Month */
            by_month: components["schemas"]["ReportByMonth"][];
            /** Count */
            count: number;
            /** Total */
            total: string;
            /** Year */
            year: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_api_v1_expenses_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                q?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_api_v1_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expenses_bulk_api_v1_expenses_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkExpensesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkExpensesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_expense_api_v1_expenses__expense_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_expense_api_v1_expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
    monthly_report_api_v1_reports_monthly_get: {
        parameters: {
            query?: {
                ym?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yearly_report_api_v1_reports_yearly_get: {
        parameters: {
            query?: {
                year?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearlyReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_transcript_api_v1_voice_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceParseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceParseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
}
